Repository Medic1111/VIRTUAL-PET, pull requests merged in 2022-11, with the labels that each got.

#11 changed font related stuff
  client/src/components/Home/Home.css
  client/src/components/LoginForm/LoginForm.css
  client/src/components/LoginForm/LoginForm.jsx
Labels: epic

#9 Server: AUTH routes with tests
  client/public/index.html
  package-lock.json
  package.json
  server/app.js
  server/config/dbconn.config.js
  server/controllers/login.js
  server/controllers/register.js
  server/controllers/validate.js
  server/index.js
  server/models/models.js
  server/routes/login.js
  server/routes/register.js
  server/routes/validate.js
  server/test/login.test.js
  server/test/register.test.js
  server/test/test.rest
  server/test/validate.test.js
Labels: epic

#14 Feature server
  server/controllers/login.js
  server/models/models.js
  server/test/login.test.js
  server/test/test.rest
Labels: task

#19 Client harris 2
  client/src/App.js
  client/src/components/Home/Home.css
  client/src/components/Home/Home.jsx
  client/src/components/LoginForm/LoginForm.css
  client/src/components/LoginForm/LoginForm.jsx
  client/src/components/RegisterForm/RegisterForm.css
  client/src/components/RegisterForm/RegisterForm.jsx
Labels: epic

#28 Feature client
  client/src/App.js
  client/src/assets/imgs/adult-kiwi.png
  client/src/assets/imgs/baby-kiwi.png
  client/src/assets/imgs/egg-gif.gif
  client/src/assets/imgs/kiwi-dead.png
  client/src/assets/imgs/old-kiwi.png
  client/src/assets/imgs/speech-bubble.svg
  client/src/assets/imgs/young-kiwi.png
  client/src/components/Home/Home.css
  client/src/components/Home/Home.jsx
  client/src/components/Main/Main.css
  client/src/components/Main/Main.jsx
  client/src/index.css
Labels: epic

#30 update
  client/src/App.js
  client/src/components/Home/Home.css
  client/src/components/Home/Home.jsx
  client/src/components/Main/Main.css
  client/src/components/Main/Main.jsx
  server/controllers/feed.js
  server/controllers/health.js
  server/controllers/play.js
  server/controllers/study.js
Labels: epic

#40 Feature server
  README.md
  adult.png
  baby.png
  dead.png
  egg.png
  home.png
  server/test/test.rest
  tamagotchi.png
Labels: documentation
